version: "3.9"

services:

  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/config/.env
    volumes:
      - ./data/:/var/lib/postgresql/data/

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8080
    env_file:
      - ./backend/config/.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./backend/config/.env
    ports:
      - "5050:80"
    volumes:
      - ./backend/config/db.json:/pgadmin4/servers.json

volumes:
  data:
